-- Database Cleanup Script: Remove Unused Tables
-- Generated by Antigravity based on codebase analysis

-- The following tables were identified as unused in the current Flutter codebase:
-- (They are either legacy Spanish versions, replaced by new tables, or not referenced in the code)

DROP TABLE IF EXISTS beneficios_top CASCADE;
DROP TABLE IF EXISTS blocks CASCADE; -- Replaced by usuarios_bloqueados
DROP TABLE IF EXISTS bloqueos CASCADE; -- Replaced by usuarios_bloqueados
DROP TABLE IF EXISTS calificaciones CASCADE; -- Replaced by referencias
DROP TABLE IF EXISTS canciones_setlist CASCADE;
DROP TABLE IF EXISTS conexiones CASCADE; -- Replaced by connections
DROP TABLE IF EXISTS conversaciones CASCADE; -- Replaced by intercom
DROP TABLE IF EXISTS eventos CASCADE; -- Replaced by gigs
DROP TABLE IF EXISTS gear_catalog CASCADE;
DROP TABLE IF EXISTS generos CASCADE;
DROP TABLE IF EXISTS generos_catalog CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS gig_lineup CASCADE; -- Replaced by event_participants
DROP TABLE IF EXISTS historial_reportes CASCADE;
DROP TABLE IF EXISTS historial_reportes_usuario CASCADE;
DROP TABLE IF EXISTS instrumentos CASCADE;
DROP TABLE IF EXISTS mensajes CASCADE; -- Replaced by intercom
DROP TABLE IF EXISTS notificaciones CASCADE; -- Replaced by notifications
DROP TABLE IF EXISTS pagos_ranking CASCADE; -- Replaced by tickets_pagos
DROP TABLE IF EXISTS perfil_gear CASCADE;
DROP TABLE IF EXISTS perfil_generos CASCADE;
DROP TABLE IF EXISTS perfiles_generos CASCADE;
DROP TABLE IF EXISTS perfiles_instrumentos CASCADE;
DROP TABLE IF EXISTS postulaciones_evento CASCADE; -- Replaced by event_invitations
DROP TABLE IF EXISTS profile_genres CASCADE;
DROP TABLE IF EXISTS puntuacion_reputacion CASCADE;
DROP TABLE IF EXISTS ranking_top CASCADE; -- Logic seems strictly profile-based now
DROP TABLE IF EXISTS reglas_reportes CASCADE;
DROP TABLE IF EXISTS reports CASCADE; -- Replaced by reportes
DROP TABLE IF EXISTS setlists CASCADE;
DROP TABLE IF EXISTS typing_indicators CASCADE; -- Handled via Supabase Realtime broadcast

-- Note: The following tables are USED and MUST NOT be deleted:
-- connections
-- device_tokens
-- event_invitations
-- event_participants
-- gigs
-- hirings
-- intercom
-- notification_settings
-- notifications
-- portfolio_media
-- post_likes (assumed used with posts)
-- posts
-- privacy_settings
-- profiles
-- referencias
-- reportes
-- tickets_pagos
-- usuarios_bloqueados
