-- Ensure Gear and Genre tables exist relative to the new code schema
-- This prevents "table not found" errors in the Profile screens

-- 1. Gear Catalog (Catálogo de equipo)
CREATE TABLE IF NOT EXISTS public.gear_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Perfil Gear (Relación Usuario - Equipo)
CREATE TABLE IF NOT EXISTS public.perfil_gear (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    gear_id BIGINT REFERENCES public.gear_catalog(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(perfil_id, gear_id)
);

-- 3. Profile Genres (Relación Usuario - Géneros)
-- Note: Code references both 'generos_perfil' and 'profile_genres'. 
-- We'll create 'generos_perfil' as valid since it was used in Edit/Profile screens mostly.
CREATE TABLE IF NOT EXISTS public.generos_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE,
    genre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(profile_id, genre)
);

-- Grant permissions just in case
GRANT ALL ON TABLE public.gear_catalog TO authenticated;
GRANT ALL ON TABLE public.gear_catalog TO service_role;
GRANT ALL ON TABLE public.perfil_gear TO authenticated;
GRANT ALL ON TABLE public.perfil_gear TO service_role;
GRANT ALL ON TABLE public.generos_perfil TO authenticated;
GRANT ALL ON TABLE public.generos_perfil TO service_role;

-- Grant functionality on sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
